[book]
authors = ["Abhinandh S"]
language = "en"
src = "src"
title = "Abhi's guide to Indian Partnership Act, 1932"

[output.html]
site-url = "/ipa/"
mathjax-support = true
additional-css = [
  "extras/css/comment-box.css",
  "extras/css/custom-callouts.css",
  "extras/css/last-changed.css",
]
additional-js = [ 
  "extras/js/custom-callouts.js",
  "extras/js/last-changed.js",
  "extras/js/comment-box.js",
]

[output.html.print]
enable = true    # include support for printable output
page-break = false # insert page-break after each chapter

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]